import mongoose from "mongoose";

// A "user" collection must be registered with Mongoose to get access the values (besides _id) from collection generated by Better Auth
// e.g. calling .populate("uploader", "name")) to display the username of a collaborator on the Project page.

export interface IUser {
  name: string;
  email: string;
  color: string;
  about: string;
  imagePath?: string | null;
}

const UserSchema = new mongoose.Schema<IUser>(
  {
    name: String,
    email: String,
    color: { type: String, default: "#808080" },
    about: { type: String, default: "" },
    imagePath: {
      type: String,
      default: null,
    },
  },
  { collection: "user" },
);

export default (mongoose.models.User as mongoose.Model<IUser>) ||
  mongoose.model<IUser>("User", UserSchema);
