import mongoose from "mongoose";

// A "user" collection must be registered with Mongoose to get access the values (besides _id) from collection generated by Better Auth
// e.g. calling .populate("uploader", "name")) to display the username of a collaborator on the Project page.

export interface IUser {
  name: string;
  email: string;
  color?: string | null;
}

const UserSchema = new mongoose.Schema<IUser>(
  {
    name: String,
    email: String,
    color: { type: String, default: null },
  },
  { collection: "user" }, // Better Auth's default collection name
);

export default (mongoose.models.User as mongoose.Model<IUser>) ||
  mongoose.model<IUser>("User", UserSchema);
